import type { ProjectFiles, FileChange } from "../ai/generator-types";
import type { FsToolResult } from "./fs-tools";

const ENV_PATH = ".env";
const ENV_EXAMPLE_PATH = ".env.example";
const ENV_TS_PATH = "src/env.ts";
const ENV_KEY_RE = /^[A-Za-z_][A-Za-z0-9_]*$/;

export const ENV_TOOL_LIMITS = {
  maxOperations: 100,
  maxValueBytes: 64 * 1024,
} as const;

interface EnvEntry {
  key: string;
  value: string;
}

function parseEnv(content: string | undefined): EnvEntry[] {
  if (!content) return [];
  const entries: EnvEntry[] = [];
  for (const rawLine of content.split("\n")) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#")) continue;
    const eqIdx = line.indexOf("=");
    if (eqIdx < 0) continue;
    const key = line.slice(0, eqIdx).trim();
    let value = line.slice(eqIdx + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    if (key) entries.push({ key, value });
  }
  return entries;
}

function textBytes(value: string): number {
  if (typeof TextEncoder !== "undefined") {
    return new TextEncoder().encode(value).length;
  }
  return value.length;
}

function validateEnvKey(key: string): string | null {
  if (!key) return "key must not be empty";
  if (!ENV_KEY_RE.test(key)) {
    return `invalid env key "${key}". Use letters, numbers, and underscores; do not start with a number.`;
  }
  return null;
}

function validateEnvValue(value: unknown): {
  ok: true;
  value: string;
} | {
  ok: false;
  error: string;
} {
  if (typeof value !== "string") {
    return { ok: false, error: "set operations require a string value" };
  }
  if (textBytes(value) > ENV_TOOL_LIMITS.maxValueBytes) {
    return {
      ok: false,
      error: `env values must be <= ${ENV_TOOL_LIMITS.maxValueBytes} bytes`,
    };
  }
  return { ok: true, value };
}

function serializeEnv(entries: EnvEntry[]): string {
  return entries
    .map(({ key, value }) => {
      const needQuote = /[\s#"']/.test(value);
      return `${key}=${needQuote ? `"${value.replace(/"/g, '\\"')}"` : value}`;
    })
    .join("\n") + (entries.length > 0 ? "\n" : "");
}

function upsertEntry(entries: EnvEntry[], key: string, value: string): EnvEntry[] {
  const next = [...entries];
  const idx = next.findIndex((e) => e.key === key);
  if (idx >= 0) {
    next[idx] = { key, value };
  } else {
    next.push({ key, value });
  }
  return next;
}

function removeEntry(entries: EnvEntry[], key: string): EnvEntry[] {
  return entries.filter((e) => e.key !== key);
}

/** Generate src/env.ts (zod schema) from .env.example entries.
 *  VITE_* keys become optional (URL-typed if the example value looks like one);
 *  other keys use the example value as a default, or .min(1) when empty. */
function generateEnvTs(exampleEntries: EnvEntry[]): string {
  if (exampleEntries.length === 0) return "";
  const lines: string[] = [];
  lines.push("// Auto-generated by manage_env — do not edit manually.");
  lines.push('import { z } from "zod";');
  lines.push("");
  lines.push("const schema = z.object({");
  for (const { key, value } of exampleEntries) {
    const isPublic = key.startsWith("VITE_");
    const looksUrl = /^https?:\/\//.test(value);
    let line: string;
    if (isPublic) {
      line = looksUrl ? "z.string().url().optional()" : "z.string().optional()";
    } else if (value) {
      const escaped = value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
      line = `z.string().default("${escaped}")`;
    } else {
      line = "z.string().min(1)";
    }
    lines.push(`  ${JSON.stringify(key)}: ${line},`);
  }
  lines.push("});");
  lines.push("");
  lines.push("export const env = schema.parse(import.meta.env);");
  lines.push("export type Env = z.infer<typeof schema>;");
  lines.push("");
  return lines.join("\n");
}

export function fsReadEnvSchema(files: ProjectFiles): FsToolResult {
  const exampleEntries = parseEnv(files[ENV_EXAMPLE_PATH]);
  const envEntries = parseEnv(files[ENV_PATH]);
  const envMap = new Map(envEntries.map((e) => [e.key, e.value]));

  const keys = exampleEntries.map((e) => ({
    key: e.key,
    isPublic: e.key.startsWith("VITE_"),
    hasValue: envMap.has(e.key) && envMap.get(e.key) !== "",
    exampleValue: e.value,
  }));

  // Report .env entries that aren't declared in .env.example — these are
  // common sources of "works locally, breaks in CI" because example is
  // missing the key.
  const declared = new Set(exampleEntries.map((e) => e.key));
  const undeclared = envEntries.filter((e) => !declared.has(e.key)).map((e) => e.key);

  const payload = {
    ok: true,
    keys,
    undeclared,
    hasEnvFile: ENV_PATH in files,
    hasExampleFile: ENV_EXAMPLE_PATH in files,
  };
  return { result: JSON.stringify(payload, null, 2), changes: [] };
}

export type ManageEnvTarget = "env" | "example";
export type ManageEnvAction = "set" | "unset";

export interface ManageEnvOp {
  target: ManageEnvTarget;
  action: ManageEnvAction;
  key: string;
  value?: string;
}

export function fsManageEnv(
  operations: ManageEnvOp[],
  generateTypedEnv: boolean,
  files: ProjectFiles,
): FsToolResult {
  if (!Array.isArray(operations) || operations.length === 0) {
    return { result: "Error: no operations provided", changes: [] };
  }
  if (operations.length > ENV_TOOL_LIMITS.maxOperations) {
    return {
      result: `Error: manage_env supports at most ${ENV_TOOL_LIMITS.maxOperations} operations at once`,
      changes: [],
    };
  }

  let envEntries = parseEnv(files[ENV_PATH]);
  let exampleEntries = parseEnv(files[ENV_EXAMPLE_PATH]);
  const warnings: string[] = [];
  const ops: string[] = [];
  let envTouched = false;
  let exampleTouched = false;

  for (const op of operations) {
    if (!op || typeof op.key !== "string" || !op.key) {
      return { result: "Error: each operation requires a non-empty 'key'", changes: [] };
    }
    const keyError = validateEnvKey(op.key);
    if (keyError) {
      return { result: `Error: ${keyError}`, changes: [] };
    }
    if (op.target !== "env" && op.target !== "example") {
      return {
        result: `Error: each operation requires target "env" or "example" (got "${String(op.target)}")`,
        changes: [],
      };
    }
    if (op.action !== "set" && op.action !== "unset") {
      return {
        result: `Error: each operation requires action "set" or "unset" (got "${String(op.action)}")`,
        changes: [],
      };
    }
    let value = "";
    if (op.action === "set") {
      const checkedValue = validateEnvValue(op.value);
      if (!checkedValue.ok) {
        return { result: `Error: ${checkedValue.error}`, changes: [] };
      }
      value = checkedValue.value;
    }
    if (op.target === "env") {
      envTouched = true;
      if (op.action === "set") {
        envEntries = upsertEntry(envEntries, op.key, value);
        ops.push(`set ${op.key}=${value === "" ? "(empty)" : value.length + " chars"}`);
        if (!exampleEntries.some((e) => e.key === op.key)) {
          warnings.push(`${op.key} not declared in .env.example`);
        }
      } else {
        envEntries = removeEntry(envEntries, op.key);
        ops.push(`unset ${op.key}`);
      }
    } else {
      exampleTouched = true;
      if (op.action === "set") {
        exampleEntries = upsertEntry(exampleEntries, op.key, value);
        ops.push(`set_example ${op.key}`);
      } else {
        exampleEntries = removeEntry(exampleEntries, op.key);
        ops.push(`unset_example ${op.key}`);
      }
    }
  }

  const newFiles: ProjectFiles = { ...files };
  const changes: FileChange[] = [];

  const writeFile = (path: string, content: string) => {
    const action: FileChange["action"] = path in files ? "modified" : "created";
    newFiles[path] = content;
    changes.push({ path, action });
  };

  if (envTouched) writeFile(ENV_PATH, serializeEnv(envEntries));
  if (exampleTouched) writeFile(ENV_EXAMPLE_PATH, serializeEnv(exampleEntries));

  let envTsNote = "";
  if (generateTypedEnv && exampleTouched) {
    const tsContent = generateEnvTs(exampleEntries);
    if (tsContent) {
      writeFile(ENV_TS_PATH, tsContent);
      envTsNote = ` Generated ${ENV_TS_PATH}.`;
    } else {
      envTsNote = " Skipped env.ts (no entries in .env.example).";
    }
  }

  const warningBlock = warnings.length > 0
    ? `\nWarnings:\n${warnings.map((w) => "  - " + w).join("\n")}`
    : "";

  return {
    result:
      `OK — applied ${ops.length} ops: ${ops.join(", ")}.${envTsNote}${warningBlock}`,
    changes,
    newFiles,
  };
}
