import { DEFAULT_ATTACHMENT_CONSTRAINTS } from "../utils/attachments";

export const MCP_LIMITS = {
  maxServers: 64,
  maxEnabledTools: 64,
  maxServerIdChars: 64,
  maxServerNameChars: 80,
  maxImportBytes: 2 * 1024 * 1024,
  maxToolNameChars: 256,
  maxToolAliasChars: 64,
  maxUrlChars: 4_096,
  maxHeaders: 64,
  maxHeaderNameChars: 128,
  maxHeaderValueBytes: 16 * 1024,
  maxCommandChars: 4_096,
  maxArgs: 128,
  maxArgBytes: 8 * 1024,
  maxEnvEntries: 128,
  maxEnvValueBytes: 64 * 1024,
  maxCwdChars: 4_096,
  minRequestTimeoutMs: 1_000,
  maxRequestTimeoutMs: 5 * 60 * 1_000,
  defaultRequestTimeoutMs: 30_000,
  maxInstructionsBytes: 128 * 1024,
  maxToolDescriptionBytes: 16 * 1024,
  maxToolSchemaBytes: 256 * 1024,
  maxResultContentBlocks: 128,
  maxResultTextBytes: DEFAULT_ATTACHMENT_CONSTRAINTS.maxFileBytes,
  maxStructuredResultBytes: DEFAULT_ATTACHMENT_CONSTRAINTS.maxFileBytes,
  maxResultAttachments: DEFAULT_ATTACHMENT_CONSTRAINTS.maxCount,
  maxResultImageBytes: DEFAULT_ATTACHMENT_CONSTRAINTS.maxImageBytes,
  maxResultFileBytes: DEFAULT_ATTACHMENT_CONSTRAINTS.maxFileBytes,
  maxResultTotalBytes: DEFAULT_ATTACHMENT_CONSTRAINTS.maxTotalBytes,
} as const;
